"""Fix user table column names - rename isActive to active, remove explicit column mappings

Revision ID: d948cbbc7be1
Revises: ec2bda80af6f
Create Date: 2026-04-28 17:40:10.344750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd948cbbc7be1'
down_revision: Union[str, None] = 'ec2bda80af6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add isVerified column with server default for existing rows
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isVerified')
    # ### end Alembic commands ###
